### ISSUE TITLE
examples broken

### ISSUE THREAD

**Issue by peppelinux** [rohe/fedservice#19]
in `fedservice/example/openid_provider/umu`

````
example/openid_provider/umu$ python3 op.py conf.json 
2022-01-19 22:34:44,332 root DEBUG Configured logging using dictionary
2022-01-19 22:34:44,333 oidcop.configure WARNING claims_interface not seems to be a valid configuration parameter
2022-01-19 22:34:44,333 oidcop.configure WARNING id_token not seems to be a valid configuration parameter
Traceback (most recent call last):
  File "op.py", line 69, in <module>
    main(args.config, args)
  File "op.py", line 37, in main
    app = oidc_provider_init_app(config)
  File "/home/wert/DEV/IdentityPython/OIDC/fedservice/example/openid_provider/umu/application.py", line 46, in oidc_provider_init_app
    app.server = init_oidc_op(app)
  File "/home/wert/DEV/IdentityPython/OIDC/fedservice/example/openid_provider/umu/application.py", line 16, in init_oidc_op
    _fed_conf.entity_id = _op_config.issuer # Works when openid_provider
  File "/home/wert/DEV/IdentityPython/OIDC/fedservice/env/lib/python3.8/site-packages/oidcmsg/configure.py", line 109, in __setattr__
    raise KeyError('{} has already been set'.format(key))
KeyError: 'entity_id has already been set'

````

in `fedservice/example/openid_relying_party/auto`

````
2022-01-19 22:33:54,070 root DEBUG Configured logging using dictionary
Traceback (most recent call last):
  File "rp.py", line 21, in <module>
    app = application.oidc_provider_init_app(conf, name, template_folder=template_dir)
  File "/home/wert/DEV/IdentityPython/OIDC/fedservice/example/openid_relying_party/auto/application.py", line 17, in oidc_provider_init_app
    app.srv_config = create_from_config_file(Configuration,
  File "/home/wert/DEV/IdentityPython/OIDC/fedservice/env/lib/python3.8/site-packages/oidcmsg/configure.py", line 239, in create_from_config_file
    return cls(_cnf,
  File "/home/wert/DEV/IdentityPython/OIDC/fedservice/env/lib/python3.8/site-packages/oidcmsg/configure.py", line 210, in __init__
    self.extend(conf=self.conf, base_path=base_path,
  File "/home/wert/DEV/IdentityPython/OIDC/fedservice/env/lib/python3.8/site-packages/oidcmsg/configure.py", line 144, in extend
    _cls(_cnf, base_path=base_path, file_attributes=file_attributes,
  File "/home/wert/DEV/IdentityPython/OIDC/fedservice/src/fedservice/configure.py", line 151, in __init__
    RPConfiguration.__init__(
TypeError: __init__() got an unexpected keyword argument 'dir_attributes'

````

**Comment by peppelinux** [comment]
pip list

````
Package            Version   Editable project location
------------------ --------- -------------------------------------------------
certifi            2021.10.8
cffi               1.15.0
charset-normalizer 2.0.8
click              8.0.3
cryptography       36.0.0
cryptojwt          1.6.1
fedservice         2.0.0     /home/wert/DEV/IdentityPython/OIDC/fedservice/src
filelock           3.4.0
Flask              2.0.2
idna               3.3
itsdangerous       2.0.1
Jinja2             3.0.3
MarkupSafe         2.0.1
oidcmsg            1.5.4
oidcop             2.3.4
oidcrp             2.1.3
pip                21.3.1
pycparser          2.21
pyOpenSSL          21.0.0
PyYAML             6.0
readerwriterlock   1.0.9
requests           2.26.0
responses          0.16.0
setuptools         58.5.3
six                1.16.0
typing_extensions  4.0.1
urllib3            1.26.7
Werkzeug           2.0.2
wheel              0.37.0
````

**Comment by peppelinux** [comment]
https://github.com/rohe/fedservice/tree/master/example#federation-example
