### ISSUE TITLE
flask_op socket not starting due to "IsADirectoryError" for "storage/fed/keyjar"

### ISSUE THREAD

**Issue by dunksten** [rohe/fedservice#9]
Hello,

currently I try to develop a prototype for the OIDC federation specification. I found this repository and tried to set up a test system according to this [README](https://github.com/rohe/fedservice/blob/master/entities/nginx_uwsgi/README.md).

Currently I managed to get nginx working as well as both RP and the signing service. But the OP server does not start because of an `IsADirectoryError: [Errno 21] Is a directory: 'storage/fed/keyjar/'`.

Here is the full log from the flask_op.log file:
```
*** Starting uWSGI 2.0.19.1 (64bit) on [Tue Aug  4 12:35:56 2020] ***
compiled with version: 9.3.0 on 04 August 2020 07:40:19
os: Linux-4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020
nodename: DESKTOP-JUAPSIS
machine: x86_64
clock source: unix
detected number of CPU cores: 8
current working directory: /home/jhansel/prototype/fedservice/entities/flask_op/uwsgi_setup
writing pidfile to /var/log/uwsgi/flask_op.pid
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
setgid() to 1000
set additional group 4 (adm)
set additional group 20 (dialout)
set additional group 24 (cdrom)
set additional group 25 (floppy)
set additional group 27 (sudo)
set additional group 29 (audio)
set additional group 30 (dip)
set additional group 44 (video)
set additional group 46 (plugdev)
set additional group 117 (netdev)
setuid() to 1000
chdir() to /home/jhansel/prototype/fedservice/entities/flask_op
your processes number limit is 50394
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address flask_op.sock fd 6
Python version: 3.8.2 (default, Jul 16 2020, 14:00:26)  [GCC 9.3.0]
PEP 405 virtualenv detected: /home/jhansel/prototype/env
Set PythonHome to /home/jhansel/prototype/env
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x563a2437e690
your server socket listen backlog is limited to 128 connections
your mercy for graceful operations on workers is 60 seconds
mapped 507880 bytes (495 KB) for 4 cores
*** Operational MODE: preforking ***
added /home/jhansel/prototype/fedservice/entities/flask_op/ to pythonpath.
2020-08-04 12:35:56,907 root DEBUG Configured logging using dictionary
2020-08-04 12:35:56,908 oidcop.configure DEBUG Set server password to {'kty': 'oct', 'use': 'sig', 'k': ''}
2020-08-04 12:35:56,918 filelock DEBUG Attempting to acquire lock 139766312838240 on storage/fed/keyjar/.lock
2020-08-04 12:35:56,919 filelock INFO Lock 139766312838240 acquired on storage/fed/keyjar/.lock
2020-08-04 12:35:56,919 filelock DEBUG Attempting to release lock 139766312838240 on storage/fed/keyjar/.lock
2020-08-04 12:35:56,919 filelock INFO Lock 139766312838240 released on storage/fed/keyjar/.lock
Traceback (most recent call last):
  File "/home/jhansel/prototype/fedservice/entities/flask_op/wsgi.py", line 57, in <module>
    app = oidc_provider_init_app(config)
  File "/home/jhansel/prototype/fedservice/entities/flask_op/application.py", line 54, in oidc_provider_init_app
    app.endpoint_context = init_oidc_op_endpoints(app)
  File "/home/jhansel/prototype/fedservice/entities/flask_op/application.py", line 25, in init_oidc_op_endpoints
    federation_entity = create_federation_entity(cwd=folder, **_fed_conf)
  File "/home/jhansel/prototype/env/lib/python3.8/site-packages/fedservice-1.0.0-py3.8.egg/fedservice/__init__.py", line 146, in create_federation_entity
    federation_entity = FederationEntity(entity_id, **args)
  File "/home/jhansel/prototype/env/lib/python3.8/site-packages/fedservice-1.0.0-py3.8.egg/fedservice/__init__.py", line 29, in __init__
    OidcContext.__init__(self, config, entity_id=entity_id)
  File "/home/jhansel/prototype/env/lib/python3.8/site-packages/oidcmsg/context.py", line 43, in __init__
    self.keyjar = self._keyjar(keyjar, self.db_conf, config, entity_id=entity_id)
  File "/home/jhansel/prototype/env/lib/python3.8/site-packages/oidcmsg/context.py", line 59, in _keyjar
    _keyjar = init_key_jar(**args)
  File "/home/jhansel/prototype/env/lib/python3.8/site-packages/cryptojwt/utils.py", line 245, in wrapper
    return f(*args, **kwargs)
  File "/home/jhansel/prototype/env/lib/python3.8/site-packages/cryptojwt/key_jar.py", line 815, in init_key_jar
    keyjar[issuer_id] = _issuer
  File "/home/jhansel/prototype/env/lib/python3.8/site-packages/cryptojwt/utils.py", line 245, in wrapper
    return f(*args, **kwargs)
  File "/home/jhansel/prototype/env/lib/python3.8/site-packages/cryptojwt/key_jar.py", line 282, in __setitem__
    self._issuers[issuer_id] = key_issuer
  File "/home/jhansel/prototype/env/lib/python3.8/site-packages/oidcmsg/storage/abfile.py", line 121, in __setitem__
    with open(fname, 'w') as fp:
IsADirectoryError: [Errno 21] Is a directory: 'storage/fed/keyjar/'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. GAME OVER ***
VACUUM: unix socket flask_op.sock removed.
```

My system is running inside WSL2, which I don't think should be the cause of this problem.
Also I am running Ubuntu 20.04.1 LTS with Python 3.8.

Some other "bugs" I could fix were:
- All the uwsgi configs need "strict=false" to support placeholders like "project=flask_op".
- The conf_uwsgi in flask_op had still http_params instead of httpc_params.

Another thing I tested was to delete the keyjar folder and instead place an empty keyjar file, but then an error came telling me that the file already exists.

I hope this helps.
Greetings Jan

**Comment by rohe** [comment]
This, I'm pretty sure is a configuration error.

In db_conf you can removed the line starting with abstract_storage_cls. It's not needed anymore.

The keyjar specification must have the handler LabeledAbstractFileSystem not AbstractFileSystem.

If you those changes the error you've encountered should go away.

Note that when installing fedservice and the underlying libraries you should get the latest versions from GitHub. 
I'm pretty sure it will not work with what's on PyPI.

**Comment by dunksten** [comment]
Hey thank you, it now works.
